FROM python:3.12-slim

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

COPY . ./app

EXPOSE 8500

CMD ["fastapi", "run", "app/API.py", "--port", "8500"]