# Stage de build
FROM node:22.14-slim as build

# Installation des dépendances globales
RUN npm install -g @angular/cli@latest

WORKDIR /app

# Copie des fichiers de configuration
COPY package*.json ./

# Installation des dépendances
RUN npm install 

# Copie du reste du code source
COPY . .

# # Build de l'application en mode production
# # Si vous utilisez Angular CLI directement
# RUN npx ng build --configuration production

# # Ou si vous préférez utiliser le script dans package.json
# # RUN npm run build -- --configuration production

# # Stage de déploiement
# FROM nginx:stable-alpine

# # Copie des fichiers de build depuis le stage précédent
# COPY --from=build /app/dist/frontend_2 /usr/share/nginx/html

# # Copie d'une configuration nginx personnalisée si nécessaire
# # COPY nginx.conf /etc/nginx/conf.d/default.conf

# Exposition du port 4200
EXPOSE 4200

# Démarrage de nginx en premier plan
CMD ["ng", "serve", "--host", "0.0.0.0"]