# Stage de build
FROM node:22.14-slim 
# as build

# Installation des dépendances globales
RUN npm install -g @angular/cli@latest

WORKDIR /app

# Copie des fichiers de configuration
COPY package*.json ./

# Installation des dépendances
RUN npm install 

# Copie du reste du code source
COPY . .

# Exposition du port 4200
EXPOSE 4200

# Démarrage de nginx en premier plan
CMD ["ng", "serve", "--host", "0.0.0.0"]